# Generated by Django 3.0.6 on 2020-06-18 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_otp_created_at'),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='uploads/images/')),
                ('gst_number', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('gst_entity', models.CharField(max_length=32)),
                ('food_license', models.CharField(blank=True, max_length=32, null=True)),
                ('drug_license', models.CharField(blank=True, max_length=16, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distributors', models.ManyToManyField(to='distributors.Distributor')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.District')),
                ('gst_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
