# Generated by Django 3.0.6 on 2020-07-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0007_auto_20200705_1422'),
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Cancelled')], default=0)),
                ('status', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.Distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.Product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.Retailer')),
            ],
        ),
    ]
