# Generated by Django 3.0.6 on 2020-07-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
