# Generated by Django 3.0.6 on 2020-06-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesman', '0001_initial'),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField()),
                ('amount', models.FloatField()),
                ('closing_balance', models.FloatField()),
                ('payment_mode', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('payment_mode', models.CharField(max_length=16)),
                ('balance', models.FloatField()),
                ('deadline', models.DateField()),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.Product')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman.Salesman')),
            ],
        ),
    ]
