# Generated by Django 3.0.6 on 2020-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20200618_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sales',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales',
            field=models.ManyToManyField(to='ledger.Sale'),
        ),
    ]
