# Generated by Django 3.0.6 on 2020-07-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0003_auto_20200706_1559'),
        ('ledger', '0004_invoice_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='salesman',
        ),
        migrations.AddField(
            model_name='invoice',
            name='salesman',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salesman.Salesman'),
            preserve_default=False,
        ),
    ]
