# Generated by Django 3.0.6 on 2020-07-07 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20200707_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default=uuid.uuid4().hex, editable=False, max_length=32, unique=True),
        ),
    ]
