# Generated by Django 3.0.6 on 2020-07-07 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_invoice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default=uuid.UUID('dd3a7464-c1ea-477a-afec-55006096920f').hex, max_length=32, unique=True),
        ),
    ]
