# Generated by Django 3.0.6 on 2020-07-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_request'),
        ('ledger', '0007_auto_20200707_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='retailer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='retailers.Retailer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='0108f1829a5c4dd9a51d658f33667c17', max_length=32, unique=True),
        ),
    ]
