# Generated by Django 3.0.6 on 2020-07-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0007_auto_20200705_1422'),
        ('retailers', '0002_request'),
        ('ledger', '0008_auto_20200707_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='distributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='distributors.Distributor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='3d015a8cb8684e4fa137ef363397525f', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField(default=0)),
                ('amount', models.FloatField()),
                ('closing_balance', models.FloatField(default=0)),
                ('last_updated_by', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.Distributor')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.Retailer')),
            ],
        ),
    ]
