# Generated by Django 3.0.6 on 2020-07-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_auto_20200707_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='d51a2ea985aa44cb9c06250c098676fa', max_length=32, unique=True),
        ),
    ]
