# Generated by Django 3.0.6 on 2020-07-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20200707_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='is_credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='548fc9326d9248bab74b9e2595d8925e', max_length=32, unique=True),
        ),
    ]
