# Generated by Django 3.0.6 on 2020-07-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_auto_20200707_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='59d4fe89368846f4afaae9bf7c2b45cb', max_length=32, unique=True),
        ),
    ]
