# Generated by Django 3.0.6 on 2020-07-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_auto_20200708_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='box',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='sch',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='sale',
            name='taxable_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='4a41f410d20b4e1fb4c031ca72be3bfe', max_length=32, unique=True),
        ),
    ]
