# Generated by Django 3.0.6 on 2020-07-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_auto_20200708_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='5d30a3287f7c4b10ab1a41d4a21dd87d', max_length=32, unique=True),
        ),
    ]
