# Generated by Django 3.0.6 on 2020-07-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_auto_20200708_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='remaining_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='4eebc4fd759f43a0a089f5080037651d', max_length=32, unique=True),
        ),
    ]
