# Generated by Django 3.0.6 on 2020-07-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_auto_20200716_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='a69b5ad3f78b4eb0b73f039b7fd69b68', max_length=32, unique=True),
        ),
    ]
