# Generated by Django 3.0.6 on 2020-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_auto_20200722_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='968c8690f1bf46f9850379a820156b04', max_length=32, unique=True),
        ),
    ]
