# Generated by Django 3.0.6 on 2020-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_auto_20200722_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='a47812eee9dd49a8b69e1882be3fb41e', max_length=32, unique=True),
        ),
    ]
