# Generated by Django 3.0.6 on 2020-07-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_auto_20200722_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='09e3993db5ff4d10a269fa5e699478a4', max_length=32, unique=True),
        ),
    ]
