# Generated by Django 3.0.6 on 2020-07-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0009_paymentmethod_paymentmode'),
        ('ledger', '0020_auto_20200722_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='payment_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.PaymentMethod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.PaymentMethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='5e35d4e94b2f45ecacdff33c7939db32', max_length=32, unique=True),
        ),
    ]
