# Generated by Django 3.0.6 on 2020-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_auto_20200731_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='5a850eb770664174b4e885516ef08b31', max_length=32, unique=True),
        ),
    ]
