# Generated by Django 3.0.6 on 2020-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_auto_20200814_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='a26dbcaf5fcf42da86fb6095c6cf05a8', max_length=32, unique=True),
        ),
    ]
