# Generated by Django 3.0.6 on 2020-08-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_auto_20200814_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='6485ee414c4243b782a8b5bfd97b19d2', max_length=32, unique=True),
        ),
    ]
