# Generated by Django 3.0.6 on 2020-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_auto_20200815_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='06b04e3e15e44149a24a18a796d0bb34', max_length=32, unique=True),
        ),
    ]
