# Generated by Django 3.0.6 on 2020-08-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_auto_20200815_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='ee0ffa76ae8e49319f1e6aeca5cf3696', max_length=32, unique=True),
        ),
    ]
