# Generated by Django 3.0.6 on 2020-08-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_auto_20200815_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='7c15338478fb4721a9d2dcd3246b6583', max_length=32, unique=True),
        ),
    ]
