# Generated by Django 3.0.6 on 2020-08-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_auto_20200815_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='656be6007f514fe5a9977581b3857e25', max_length=32, unique=True),
        ),
    ]
