# Generated by Django 3.0.6 on 2020-06-18 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.ImageField(null=True, upload_to='uploads/images/')),
                ('gst_number', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('gst_entity', models.CharField(max_length=32)),
                ('drug_license', models.CharField(blank=True, max_length=16, null=True)),
                ('food_license', models.CharField(blank=True, max_length=32, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.District')),
                ('gst_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('duration', models.IntegerField(help_text='Total months this packages will work')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distributors.Distributor')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=256)),
                ('payment_date', models.DateField()),
                ('distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distributors.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('description', models.TextField()),
                ('mrp', models.FloatField()),
                ('hsn', models.CharField(max_length=16)),
                ('base_price', models.FloatField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.Distributor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.Subscription')),
            ],
        ),
    ]
