# Generated by Django 3.0.6 on 2020-06-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_auto_20200618_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Distributor'),
            preserve_default=False,
        ),
    ]
