# Generated by Django 3.0.6 on 2020-06-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0004_type_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
