# Generated by Django 3.0.6 on 2020-07-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0007_auto_20200705_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
