# Generated by Django 3.0.6 on 2020-08-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0011_auto_20200814_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='due',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
