# Generated by Django 3.0.6 on 2020-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0012_auto_20200815_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='transaction_id',
            field=models.UUIDField(),
        ),
    ]
