# Generated by Django 3.0.6 on 2020-07-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0003_auto_20200716_2248'),
        ('logs', '0002_auto_20200705_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retailers.Retailer')),
            ],
        ),
    ]
