# Generated by Django 3.0.6 on 2020-07-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0008_product_is_deleted'),
        ('logs', '0004_notifications_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='distributors.Distributor'),
            preserve_default=False,
        ),
    ]
